// Curated "featured customers" — notable brands with real domains for crisp logos.
// `logo` (a local /logos/* file or URL) overrides the favicon when provided.
export type FeaturedBrand = { name: string; domain: string; logo?: string };

export const featuredBrands: FeaturedBrand[] = [
  { name: "AAFT University", domain: "aaft.edu.in" },
  { name: "Advanced Hair Studio", domain: "advancedhairstudioindia.com" },
  { name: "Agaro Lifestyle", domain: "agarolifestyle.com" },
  { name: "AlaanPay", domain: "alaan.com" },
  { name: "Amama Jewels", domain: "amama.in" },
  { name: "Astro Arun Pandit", domain: "astroarunpandit.org" },
  { name: "Aurelia Diamonds", domain: "aureliadiamonds.com" },
  { name: "Beeaar Group", domain: "beeaar.com" },
  { name: "Bizgurukul", domain: "bizgurukul.com" },
  { name: "Boldfit", domain: "boldfit.in" },
  { name: "CarInfo", domain: "carinfo.app" },
  { name: "Century Real Estate", domain: "centuryrealestate.in" },
  { name: "Christ University", domain: "christuniversity.in", logo: "/logos/christ-university.jpg" },
  { name: "Cornitos", domain: "cornitos.com" },
  { name: "Corvi LED", domain: "corvi.com" },
  { name: "CP Goenka International School", domain: "cpgoenkainternationalschool.com" },
  { name: "Dabur", domain: "dabur.com" },
  { name: "Dermawear", domain: "dermawear.co.in" },
  { name: "Dista USA", domain: "distacart.com" },
  { name: "Distacart", domain: "distacart.com" },
  { name: "Europe Emirates Group", domain: "uae-eu.com" },
  { name: "ExpenseOnDemand", domain: "expenseondemand.com" },
  { name: "Farmley", domain: "farmley.com" },
  { name: "Frido", domain: "myfrido.com" },
  { name: "GemsMantra", domain: "gemsmantra.com" },
  { name: "GK Hair", domain: "gkhair.com" },
  { name: "Goodveda", domain: "goodveda.com" },
  { name: "Gujarat Titans", domain: "gujarattitansipl.com" },
  { name: "Hero Homes", domain: "herohomes.in" },
  { name: "IDP India", domain: "idp.com", logo: "/logos/idp.ico" },
  { name: "Indus Valley", domain: "buyindusvalley.in" },
  { name: "Jiva Ayurveda", domain: "jiva.com" },
  { name: "Lal Sweets India", domain: "lalsweets.com" },
  { name: "Major Hospital", domain: "majorsuperspeciality.com" },
  { name: "Manav Rachna Edu", domain: "manavrachna.edu.in" },
  { name: "Melange Singapore", domain: "melangesingapore.com" },
  { name: "Menoveda", domain: "menoveda.com" },
  { name: "Metalkart", domain: "metalkart.in" },
  { name: "Motherland Hospital", domain: "motherlandhospital.com" },
  { name: "NasAcademy", domain: "nasacademy.com" },
  { name: "Nestroots", domain: "nestroots.com" },
  { name: "pH Laboratories", domain: "phlaboratories.com" },
  { name: "PrimeStyle.com", domain: "primestyle.com" },
  { name: "Priyagold", domain: "priyagold.com" },
  { name: "Project Serotonin", domain: "sr.tn" },
  { name: "Rage Coffee", domain: "ragecoffee.com" },
  { name: "Renee Cosmetics", domain: "reneecosmetics.in" },
  { name: "Revibe", domain: "revibe.me" },
  { name: "Saraswat Hospital", domain: "saraswathospital.com" },
  { name: "Shiseido Professional", domain: "shiseido-professional.com" },
  { name: "Shivam Autozone", domain: "shivamautozone.com" },
  { name: "Shree Ashtech", domain: "shreelog.com" },
  { name: "Soham", domain: "sohamliveyour150.com" },
  { name: "Sploot", domain: "sploot.space" },
  { name: "Suwasthi", domain: "suwasthi.com" },
  { name: "TDF Diamonds", domain: "tdfjewellery.com" },
  { name: "The Akshaya Patra Foundation", domain: "akshayapatra.org" },
  { name: "The Art of Living", domain: "artofliving.org" },
  { name: "The Next Decor", domain: "the-next-decor.com" },
  { name: "The Pillow Company", domain: "thepillowcompany.in" },
  { name: "Uptownie", domain: "uptownie.com" },
  { name: "VehicleCare", domain: "vehiclecare.in" },
];
