import fs from "fs";
import path from "path";

const featSrc = fs.readFileSync(
  "/Users/rinkeshsingh/portfolio/src/lib/featured.ts",
  "utf8"
);
// crude parse of { name: "..", domain: ".." }
const brands = [...featSrc.matchAll(/name:\s*"([^"]+)",\s*domain:\s*"([^"]+)"/g)].map(
  (m) => ({ name: m[1], domain: m[2] })
);

const OUT = "/Users/rinkeshsingh/portfolio/public/logos";
const slug = (s) => s.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");
const UA = { "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7)" };
const abs = (href, base) => {
  try { return new URL(href, base).href; } catch { return null; }
};
const extOf = (ct) =>
  ct.includes("svg") ? "svg" : ct.includes("png") ? "png" : ct.includes("jpeg") || ct.includes("jpg") ? "jpg" : ct.includes("webp") ? "webp" : ct.includes("icon") ? "ico" : "";

async function tryFetch(url, ms = 8000) {
  const ctrl = new AbortController();
  const t = setTimeout(() => ctrl.abort(), ms);
  try {
    const r = await fetch(url, { headers: UA, signal: ctrl.signal, redirect: "follow" });
    clearTimeout(t);
    return r;
  } catch { clearTimeout(t); return null; }
}

function pickLogos(html, base) {
  const cands = [];
  const push = (href, rank) => { const u = abs(href, base); if (u) cands.push({ u, rank }); };
  // apple-touch-icon (clean square) — highest
  for (const m of html.matchAll(/<link[^>]+rel=["'][^"']*apple-touch-icon[^"']*["'][^>]*>/gi)) {
    const h = m[0].match(/href=["']([^"']+)["']/i); if (h) push(h[1], 1);
  }
  // svg icon
  for (const m of html.matchAll(/<link[^>]+rel=["'][^"']*icon[^"']*["'][^>]*>/gi)) {
    const h = m[0].match(/href=["']([^"']+)["']/i);
    const isSvg = /svg/i.test(m[0]) || (h && /\.svg/i.test(h[1]));
    if (h) push(h[1], isSvg ? 2 : 4);
  }
  // og:image
  const og = html.match(/<meta[^>]+property=["']og:image["'][^>]*content=["']([^"']+)["']/i)
    || html.match(/<meta[^>]+content=["']([^"']+)["'][^>]*property=["']og:image["']/i);
  if (og) push(og[1], 3);
  cands.sort((a, b) => a.rank - b.rank);
  return cands;
}

const manifest = {};
const report = [];
for (const b of brands) {
  const base = `https://${b.domain}`;
  let saved = null;
  const home = await tryFetch(base);
  const html = home && home.ok ? await home.text() : "";
  const cands = html ? pickLogos(html, base) : [];
  cands.push({ u: `${base}/favicon.ico`, rank: 5 });
  for (const c of cands) {
    const r = await tryFetch(c.u);
    if (!r || !r.ok) continue;
    const ct = r.headers.get("content-type") || "";
    if (!ct.startsWith("image")) continue;
    const ext = extOf(ct);
    if (!ext) continue;
    const buf = Buffer.from(await r.arrayBuffer());
    if (buf.length < 200) continue; // skip empty/broken
    const file = `${slug(b.name)}.${ext}`;
    fs.writeFileSync(path.join(OUT, file), buf);
    saved = `/logos/${file}`;
    break;
  }
  if (saved) { manifest[slug(b.name)] = saved; report.push(`OK   ${b.name} -> ${saved}`); }
  else report.push(`MISS ${b.name}`);
}

fs.writeFileSync(
  "/Users/rinkeshsingh/portfolio/src/lib/logoManifest.ts",
  `// AUTO-GENERATED by scratchpad/fetch-logos.mjs\nexport const logoManifest: Record<string, string> = ${JSON.stringify(manifest, null, 2)};\n`
);

console.log(report.join("\n"));
console.log(`\n${Object.keys(manifest).length}/${brands.length} logos downloaded`);
